spring.application.name=Tienda_Generica_Distribuidos

spring.datasource.url=jdbc:postgresql://localhost:5432/DB_Tienda_Sis_Dis
spring.datasource.username=postgres
spring.datasource.password=Admin2025

spring.datasource.driver-class-name=org.postgresql.Driver
